### ISSUE TITLE
Deleting an item selects the next one on button release

### ISSUE THREAD

**Issue by bfedie518** [rainlizard/ScriptNameOnTop#3]
When you delete an item, if your mouse is hovering over another script when you let go of right click, it selects and switches to that script.
![script_name_delete_selects_next](https://user-images.githubusercontent.com/17280776/199570425-4c22957f-9b85-4f06-bc14-d2720c607f55.gif)

The weird part is that `PopupMenu` doesn't select on right-click, so there's no reason `id_pressed` should be firing.  You can see that right-clicking normally does nothing if you disable that part of the plugin code.

Interestingly, it doesn't select it if you disable refreshing the popup menu on item deletion.  Commenting out the `show_popup()` line (and adding `pass` to make the `if` compile) means you don't get the instant box shrink, but it no longer selects the next script either.
https://github.com/rainlizard/ScriptNameOnTop/blob/765d6848c78c65d7447ad4de2b3fef410379fe55/addons/script-name-on-top/plugin.gd#L161-L163

**Comment by rainlizard** [comment]
fixed: https://github.com/rainlizard/ScriptNameOnTop/commit/77f6913ec73e7403f982c06daed8c81ffed5118e

I was going to use mouse_filter = ignore (for 1 frame), but PopupMenu no longer inheriting Control in Godot 4.0 means a ton of possibilities like that aren't allowed anymore, which is unfortunate. This hacky solution works well enough though.
